# Generated by Django 4.0.5 on 2022-06-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='facebook url', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(default='linkedin url', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='Twitter url', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='First name', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='last name', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.TextField(default='Phone', max_length=20),
        ),
    ]
