# Generated by Django 4.0.5 on 2022-06-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_facebook_profile_linkedin_profile_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='Phone', max_length=20),
        ),
    ]
